[phases.setup]
nixPkgs = ["nodejs_22", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile --config.optional=true"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "pnpm start -- --port ${PORT:-8999}"
